export const OBTENER_TODOS_LIBROS = 'OBTENER_TODOS_LIBROS';
export const OBTENER_LIBRO_POR_ID = 'OBTENER_LIBRO_POR_ID';
export const AGREGAR_LIBRO = 'AGREGAR_LIBRO';
export const ELIMINAR_LIBRO = 'ELIMINAR_LIBRO';
export const ACTUALIZAR_LIBRO = 'ACTUALIZAR_LIBRO';
export const FILTRAR_LIBROS = 'FILTRAR_LIBROS';
export const QUITAR_FILTRO = 'LIMPIAR_FILTRO';
export const ORDENAR_LIBROS = 'ORDENAR_LIBROS';
export const QUITAR_ORDEN = 'LIMPIAR_ORDEN';
export const SIGUIENTE_PAGINA = 'SIGUIENTE_PAGINA';
export const PAGINA_ANTERIOR = 'PAGINA_ANTERIOR';
export const AGREGAR_LOCALIZACION = 'AGREGAR_LOCALIZACION';
export const BUSCAR_LIBRO_POR_TITULO = 'BUSCAR_LIBRO_POR_TITULO';
export const DETALLE_LIBRO = 'DETALLE_LIBRO';
export const BORRA_LIBROCARRO = 'BORRA_LIBROCARRO';
 
export const LOGIN_USER ='LOGIN_USER';
export const LOGOUT_USER ='LOGOUT_USER';
